

services:
  postgres:
    image: postgres:17-alpine
    container_name: attendance_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secure_password_123
      POSTGRES_DB: attendance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
